sdatkinson/NeuralAmpModelerCore

dsp/dsp.cpp
dsp/dsp.h
dsp/wavenet.cpp

This adds support for the "Hardtanh" activation function in WaveNet models. It will have no impact on current models.
My (admittedly limited so far) testing indicates that using a hard tanh activation function (basically clamp to -1/1) results in the same ESR as using a regular tanh. But it is ***much*** faster to compute.
It seems to perform about the same as the fast tanh function that is currently disabled, but might be able to be further optimized with SSE magic. It also has the benefit of being available as an activation fuction in pytorch.
If we get it implemented here, now - once it has been out in the wild for a bit we can switch to using it in training (maybe by default, maybe an option, maybe only on lite/feather?)
If you want to test training a model with it, just swap out …

Added Hardtanh activation function

---

NAM/dsp.cpp

This makes sure we don't get double promotion in the fast tanh function.
I suspect that fast tanh will be superseded by hard tanh before it sees the light of day, but just in case...

fabs->fabsf in fast tanh

---

.clang-format
NAM/activations.h
NAM/dsp.cpp
NAM/dsp.h
NAM/get_dsp.cpp
NAM/lstm.cpp
NAM/lstm.h
NAM/util.cpp
NAM/util.h
NAM/wavenet.cpp
NAM/wavenet.h
dsp/ImpulseResponse.cpp
dsp/ImpulseResponse.h
dsp/NoiseGate.cpp
dsp/NoiseGate.h
dsp/RecursiveLinearFilter.cpp
dsp/RecursiveLinearFilter.h
dsp/Resample.h
dsp/dsp.cpp
dsp/dsp.h
dsp/wav.cpp
dsp/wav.h
format.sh

A new formatting style. Wow, much nicer on the eyes!
Taken from https://github.com/sdatkinson/NeuralAmpModelerPlugin/pull/162 (thanks, @olilarkin !)

Formatting

---

NAM/activations.cpp
NAM/activations.h
NAM/convnet.cpp
NAM/convnet.h
NAM/dsp.cpp
NAM/dsp.h
NAM/lstm.cpp
NAM/wavenet.cpp
NAM/wavenet.h

This PR refactors the activation function handling. It does the following:
- centralizes activation functions in activation.h/activation.cpp
- does function lookup by name at model initialization
- ensures that all activation function application is done in efficient block operations
It also adds a flag to turn on and off the fast tanh approximation. You just need to do call "**activations::Activation::enable_fast_tanh()**" before loading a model. Even with the potential of "Hardtanh" replacing it, it probably makes sense to implement this given all of the existing models out there that could be sped up. Maybe a toggle switch in the UI ("Fast Mode")?
I haven't yet switched over the LSTM code, and there are also some hardcoded sigmoids in the WaveNet code.

Activation function refactor

---

NAM/dsp.h

Adding method determining whether model has configured loudness parameter. If current loudness is equal to the default one - normalisation wont occur. This is a compromise to avoid passing unnecessary bool param to the model.
(partially) Fixes sdatkinson/NeuralAmpModelerPlugin#183
This is a first of 2 parts to resolve ☝️ issue.

Method to determine whether model has loudness data

---

NAM/activations.h

This PR just cleans up the Activation class constructor/destructors. It wasn't currently a problem (although it could have been in the future), but it gits rid of a bunch of annoying compiler warnings.

Activation constructor/destructor cleanup

---

dsp/wav.cpp
dsp/wav.h

Whilst working on the plug-in code it seemed moving this here would make sense

Add wav error message string function to dsp::wav

---

NAM/dsp.h
NAM/get_dsp.cpp

Yarr, we meet again!
I've now branched this dspStruct thingy into a separate branch, updated to latest changes and let's hope it works this time. :o) I've compiled without errors, NAM runs and only the dspStruct addition is now present in this pull request.
Original text from #31 : Just the dspData struct addition, I added the metadata as a JSON as I don't know the exact properties (and I guess they are still on poll anyways?) but we can always add more specific data in in the future I guess.
This replaces #31 and resolves #45

dspStruct pull request

---

NAM/activations.cpp
NAM/activations.h
NAM/lstm.cpp

This PR adds fast tanh and fast sigmoid activation for LSTM models. It keys off of the enable_fast_tanh()/disable_fast_tanh() methods.
My testing indicates around a 40% performance improvement for LSTM models.

Add fast tanh and fast sigmoid to LSTM

---

.github/workflows/build.yml
.gitmodules
CMakeLists.txt
Dependencies/nlohmann/json.hpp
build/.gitignore
tools/CMakeLists.txt
tools/benchmodel.cpp
tools/loadmodel.cpp

The PR adds  a CMake build processes to allow checking buildability as well as creating some tools.
Right now, the only tool is a simple "loadmodel" program, but it is sufficient to test whether the core NAM code compiles.
To enable building, I added the Eigen and json.hpp dependencies to this repo.

Add CMake build tools

---

dsp/NoiseGate.cpp
dsp/RecursiveLinearFilter.cpp
dsp/wav.cpp

Some errors came up when I was building a JUCE project in Linux. So, quick fix.

Fix minor incompatibilities with clang/g++ build on Linux

---

NAM/get_dsp.cpp
dsp/ImpulseResponse.cpp
dsp/wav.cpp
tools/benchmodel.cpp

Fix memory issues

---

NAM/convnet.cpp
NAM/dsp.cpp
NAM/get_dsp.cpp
NAM/lstm.cpp
NAM/wavenet.cpp
NAM/wavenet.h

This PR fixes several compiler warnings generated by GCC under Linux.
They are quite a few but related to just 2 issues:
1. Comparison of signed vs unsigned types (because `std::vector<>::size()` returns `size_t` which is unsigned)
2. C++ class constructors have wrong member initialization order

Fix compiler warnings

---

NAM/convnet.cpp
NAM/convnet.h
NAM/dsp.cpp
NAM/dsp.h
NAM/get_dsp.cpp
NAM/lstm.cpp
NAM/lstm.h
NAM/wavenet.cpp
NAM/wavenet.h

Implements `DSP::GetExpectedSampleRate()` and needed extensions to subclasses.
Resolves #57

Implement expected sample rate for DSP class

---

dsp/ImpulseResponse.cpp
dsp/ImpulseResponse.h

Few changes that will enable loading models from serialized sources:
- added IR snapshot - a small struct that will allow to capture current IR configuration, and then recover IR basing on it
- added new method that allows to create DSP basing on directly passed json config instead of file path. 
This is a first part of the solution for issue sdatkinson/NeuralAmpModelerPlugin#163 second part is here: https://github.com/sdatkinson/NeuralAmpModelerPlugin/pull/206

DSPs prepared for loading persisted models

---

dsp/wav.cpp

when the subchunk1Size>16 because the rounded to dword offset calculation was wrong.
Now IR's such as BD_HV_Creamback3_mixed.wav  (in [free pack from Bogren Digital Impulses](https://bogrendigital.com/pages/free-ir-pack)) load perfectly while other common cases (chunk size = 16) still work fine.

Fix some wav impulse files would sometimes fail to load ... 

---

dsp/NoiseGate.cpp
dsp/NoiseGate.h
dsp/RecursiveLinearFilter.cpp
dsp/RecursiveLinearFilter.h
dsp/dsp.cpp
dsp/dsp.h

This replaces double I/O for the dsp classes with DSP_SAMPLE. It is set to double by default (so no change for the NAM plugin) but can be switched to float by setting DSP_SAMPLE_FLOAT.
This is similar to the change made to the NAM code. I used a separate define to allow the dsp code to run at a different sample rate if needed/desired.
I just changed the I/O and left parameters as double.

Allow defining DSP_SAMPLE_FLOAT to have dsp classes use float I/O

---

NAM/convnet.cpp
NAM/dsp.cpp
NAM/util.cpp
NAM/util.h
NAM/wavenet.cpp

I used _valgrind_ to test my audio plugin, and it spat out a bunch of warnings like this one:
```
==61792== Conditional jump or move depends on uninitialised value(s)
==61792==    at 0x4D4CB77: tanhf (s_tanhf.c:36)
==61792==    by 0x461359: std::tanh(float) (cmath:502)
==61792==    by 0xACCF70: activations::ActivationTanh::apply(float*, long) (activations.h:70)
==61792==    by 0xACCEF9: activations::Activation::apply(Eigen::Block<Eigen::Matrix<float, -1, -1, 0, -1, -1>, -1, -1, true>) (activations.h:50)
==61792==    by 0xAD086B: convnet::ConvNetBlock::process_(Eigen::Matrix<float, -1, -1, 0, -1, -1> const&, Eigen::Matrix<float, -1, -1, 0, -1, -1>&, long, long) const (convnet.cpp:71)
==61792==    by 0xAD10A9: convnet::ConvNet::_process_core_() (convnet.cpp:129)
==61792==    by 0xAD6E69: …
```

Fix some buffers having uninitialized contents after resizing

---

NAM/wavenet.cpp
NAM/wavenet.h

This PR switches WaveNet from using the current anti-pop method to pre-warming the model over the size of the receptive field on creation.
This has the advantage that the pre-warming isn't done during real-time processing, and it also does not need the volume ramped-in transition.
I used a single-sample buffer for simplicity, and to be conservative since we do not yet know the buffer size. I figure there isn't much cross-sample optimization happening anyway. This could be changed if we get around to telling the model its maximum audio buffer size.

Pre-warm WaveNet on creation over the size of the receptive field

---

NAM/convnet.cpp
NAM/dsp.cpp
NAM/dsp.h
NAM/lstm.cpp
NAM/wavenet.cpp
tools/benchmodel.cpp

This PR cleans up and simplifies the processing interface by doing the following:
- Removes input/output gain parameters.
- Removes model "params" dictionary parameter.
- Switches from multi-channel inputs/outputs to single mono input/output.
- Removes extra input/output buffers and input copy
The process call is now just simply:
`void DSP::process(NAM_SAMPLE* input, NAM_SAMPLE* output, const int num_frames)`
This mostly is just a benefit for simplicity of interface, although for simple models like LSTM, it *might* make for a small noticeable performance increase.
@sdatkinson - note that I just removed the model parameter dictionary from the process call. I didn't take out the internal code using it - I figured that is better done by you.
I've tested WaveNet and LSTM, but not ConvNet. …

Processing interface cleanup

---

NAM/convnet.cpp
NAM/convnet.h
NAM/dsp.cpp
NAM/dsp.h
NAM/lstm.cpp
NAM/lstm.h
NAM/wavenet.cpp
NAM/wavenet.h

Removed _process_core(). Pass input/output/num_frames where needed instead of caching in local variables. Removed output normalization. Added functions for getting model normalization factor in dB and linear gain.
I also removed the anti-pop code for ConvNet - it needs to be replaced with a pre-warm.
Resolves https://github.com/sdatkinson/NeuralAmpModelerCore/issues/79

Remove _process_core() and output normalization

---

NAM/convnet.cpp
NAM/dsp.cpp
NAM/dsp.h
NAM/get_dsp.cpp
NAM/lstm.cpp
NAM/util.h
NAM/wavenet.cpp

Resolves #82 
Remove `TARGET_DSP_LOUDNESS`
Implement functions for loudness API:
* `HasLoudness()`
* `GetLoudness()`
* `SetLoudness()`

[BREAKING] Remove `TARGET_DSP_LOUDNESS`

---

NAM/convnet.cpp
NAM/convnet.h
NAM/dsp.cpp
NAM/dsp.h
NAM/get_dsp.cpp
NAM/lstm.cpp
NAM/lstm.h
NAM/wavenet.cpp
NAM/wavenet.h

Use `SetLoudness()` after construction instead.
Resolves #86
A few other cleanups in there too 🙂

[BREAKING] Remove constructors with loudness

---

NAM/convnet.cpp
NAM/dsp.cpp
NAM/dsp.h
NAM/get_dsp.cpp
NAM/wavenet.cpp
NAM/wavenet.h

This PR adds a prewarm() method to the DSP base class that gets called from get_dsp().
The default behavior is to process the model over "_prewarm_samples" samples. By default, this is 0 - so nothing happens for LSTM (which is what we want).
WaveNet and ConvNet both set "_prewarm_samples" to the size of the model's receptive field.
@sdatkinson I don't use ConvNet, so I'm not sure I got the receptive field correct - can you make sure to check it?
Resolves https://github.com/sdatkinson/NeuralAmpModelerCore/issues/89
Resolves https://github.com/sdatkinson/NeuralAmpModelerCore/issues/61

Moved pre-warm to DSP and call it in get_dsp()

---

NAM/convnet.cpp
NAM/convnet.h
NAM/dsp.cpp
NAM/dsp.h
NAM/get_dsp.cpp
NAM/lstm.cpp
NAM/lstm.h
NAM/wavenet.cpp
NAM/wavenet.h

Resolves #81.
Also renaming "params" variables to "weights" where it's referring to _model weights_ (aka parameters, but since I've used "parametric" in NAM to refer to modeling that's parameterized wrt "real world" parameters, I want it to not be confusing).
Note: I've attempted to leave in hooks in locations where extending this library's classes to recover the parametric functionality can be done by downstream projects who are interested in it without having to tear up too much code. Hence the virtual methods in the WaveNet, e.g.

[BREAKING] Remove parametric modeling code

---

NAM/dsp.h

Hotfix renaming `i_cols` in `dsp.h` to `ncols` like in `dsp.cpp`
Related to #104

Bug fix renaming param in header to implementation

---

NAM/convnet.cpp
NAM/convnet.h
NAM/dsp.cpp
NAM/dsp.h
NAM/lstm.cpp
NAM/lstm.h
NAM/wavenet.cpp
NAM/wavenet.h
tools/benchmodel.cpp

This function will handle e.g. pre-allocation duties. It will _not_ run `nam::DSP::prewarm()`. For that, use `ResetAndPrewarm()` (TBD)
Resolves #96.

Define `nam::DSP::Reset` and `nam::DSP::ResetAndPrewarm`

---

.github/workflows/build.yml
NAM/dsp.h
tools/CMakeLists.txt
tools/run_tests.cpp
tools/test/test_dsp.cpp

* Resolves #117 
* Resolves #116

[FEATURE] Define input and output level calibration functionality for `DSP`

---

NAM/convnet.h
NAM/get_dsp.h
NAM/wavenet.h

[Chore] Formatting

---

NAM/wavenet.cpp
tools/run_tests.cpp
tools/test/test_wavenet.cpp

Resolves #101.
Not sure it's very efficient but at least we're correct again.

[BUGFIX] Fix gated activations in WaveNet

---

NAM/convnet.h
NAM/wavenet.h

[BUGFIX] Fix some wrongly-private attributes in WaveNet
